# Generated by Django 5.1 on 2025-05-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadoReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoReporter', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='estadoTecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rangos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rango', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='regisODN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('odn', models.TextField(max_length=250)),
                ('olt', models.TextField(max_length=250)),
                ('cantidadFat', models.IntegerField()),
                ('direccion', models.TextField(max_length=350)),
                ('observacion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RespaldoNinja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150, null=True)),
                ('apellido', models.TextField(max_length=150, null=True)),
                ('cedula', models.TextField(max_length=150, null=True)),
                ('fat', models.TextField(max_length=150, null=True)),
                ('correo', models.TextField(max_length=150, null=True)),
                ('cuadrilla', models.TextField(max_length=150, null=True)),
                ('odn', models.TextField(max_length=150, null=True)),
                ('telefono', models.TextField(max_length=150, null=True)),
                ('potencia_casa', models.TextField(max_length=150, null=True)),
                ('potencia_fat', models.TextField(max_length=150, null=True)),
                ('rango', models.TextField(max_length=150, null=True)),
                ('fecha_retiro', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('apellido', models.TextField(max_length=200)),
                ('cedula', models.TextField(max_length=8, unique=True)),
                ('telefono', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('eliminado', models.BooleanField(default=False)),
                ('tipo_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.rangos')),
            ],
        ),
        migrations.CreateModel(
            name='regisFAT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccionFat', models.TextField(max_length=150)),
                ('observacionFat', models.TextField(max_length=150, null=True)),
                ('fat', models.TextField(max_length=150)),
                ('dato_fat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.regisodn')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('apellido', models.TextField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('cuadrilla', models.CharField(max_length=100)),
                ('posicion_fat', models.CharField(max_length=100)),
                ('potencia_fat', models.CharField(max_length=100)),
                ('potencia_casa', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('correo', models.EmailField(max_length=150)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.planes')),
                ('tipo_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.rangos')),
                ('fat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.regisfat')),
                ('ond_fat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.regisodn')),
            ],
        ),
        migrations.CreateModel(
            name='reporteCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(max_length=250)),
                ('falla', models.TextField(max_length=250, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('valor', models.BooleanField()),
                ('capture', models.ImageField(blank=True, null=True, upload_to='testeos/')),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('luces', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('DatosCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.estadoreporte')),
                ('status_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadoReporte_admin', to='cantv_sistema.estadoreporte')),
            ],
        ),
        migrations.CreateModel(
            name='subAdmin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('apellido', models.TextField(max_length=200)),
                ('cedula', models.TextField(max_length=8, unique=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('telefono', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('tipo_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.rangos')),
            ],
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('apellido', models.TextField(max_length=200)),
                ('cedula', models.TextField(max_length=8, unique=True)),
                ('huella', models.TextField(max_length=120, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('telefono', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.estadotecnico')),
                ('tipo_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.rangos')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.admin')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.cliente')),
                ('sub_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.subadmin')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='reportesParaTecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DatosCliente_id', models.BigIntegerField(blank=True, null=True)),
                ('DatosCliente_nombre', models.TextField(blank=True, null=True)),
                ('DatosCliente_cedula', models.TextField(blank=True, null=True)),
                ('DatosCliente_falla', models.TextField(blank=True, null=True)),
                ('DatosCliente_FechaCreacion', models.DateTimeField(null=True)),
                ('mas_informacion_tecnico', models.TextField(max_length=255, null=True)),
                ('fecha_gestion', models.DateTimeField(null=True)),
                ('DatosReporteCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cantv_sistema.reportecliente')),
                ('Datos_Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cantv_sistema.cliente')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.estadoreporte')),
                ('DatosTecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.tecnico')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.tiporeporte')),
            ],
        ),
        migrations.CreateModel(
            name='peticionesCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peticion', models.TextField(max_length=150, null=True)),
                ('tema', models.TextField(max_length=150, null=True)),
                ('datosCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.cliente')),
                ('tipo_de_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.tiporeporte')),
            ],
        ),
        migrations.CreateModel(
            name='tiposPermisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPermiso', models.TextField(max_length=150)),
                ('descripcion', models.TextField(max_length=250, null=True)),
                ('estadoPermiso', models.BooleanField(default=False)),
                ('admins_con_permiso', models.ManyToManyField(through='cantv_sistema.Permiso', to='cantv_sistema.admin')),
            ],
        ),
        migrations.AddField(
            model_name='permiso',
            name='tipo_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantv_sistema.tipospermisos'),
        ),
    ]
